### ISSUE TITLE
iCub_sn_050 - Sostituzione  cod. 3320 con versione successiva cod 3320.A1- RC_TLR_011_P_051 Rev.A1

### ISSUE THREAD

**Issue by GiacomoVassallo13** [icub-tech-iit/robot-snapshots#11]
**Applicant:** Giacomo Vassallo, @GiacomoVassallo13 

**Snapshot name:** iCub_sn_050

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Sostituzione pezzo cod 3320 - RC_TLR_011_P_051 con la sua versione successiva, cod 3320.A1 - RC_TLR_011_P_051 Rev.A1  analisi del problema nel commento: https://github.com/icub-tech-iit/proto/issues/1977#issuecomment-1294769716

[Optional table]

| Item / IITCODE | Alias  | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|:---|
| 3320 |   RC_TLR_011_P_051   |1pz  | SHEATH SUPPORT - RIGHT HAND | rev A1 |
|  |  |  |  |  |
|  |  |  |  |  |
|  |  |  |  |  |

## Definition of Done
Bisogna modificare lo snapshot del robot per sostituire il pezzo. Lo snapshot deve essere uguale al robot reale.

**Comment by Elio75** [comment]
@GiacomoVassallo13 richiesta eseguita vedere [issue#1964](https://github.com/icub-tech-iit/proto/issues/1964#issuecomment-1294960292)

@Fabrizio69

**Comment by Fabrizio69** [comment]
> @GiacomoVassallo13 richiesta eseguita sullo snapshot iCub2.7 SN-050, vedere [issue#1964](https://github.com/icub-tech-iit/proto/issues/1964#issuecomment-1294960292)
> 
> @Fabrizio69

Procediamo quindi alla chiusura di questa issue
