### ISSUE TITLE
ergocub_sn_000 - lower arms implementation

### ISSUE THREAD

**Issue by Lawproto** [icub-tech-iit/robot-snapshots#13]
**Applicant:** *Lorenzo Protopapa*, @Lawproto 
cc @fiorisi 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Implement both full lower arms - currently missing - in the robot. Namely:
- `ECUB_004_A_004.ASM`
- `ECUB_004_A_005.ASM`

found in `ergocub-design-lowerarm repository`, `mech` branch

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
Above mentioned aliases implemented with the right positioning.

## Commit

- [commit](https://github.com/icub-tech-iit/robot-snapshots/commit/652c6e274b7fd34b543eba950bf8d905d50c3214)

**Comment by Lawproto** [comment]
@Fabrizio69 @fiorisi in my opinion, pull requests have a good potential for these kind of tasks. They act as an issue while simultaneously prompting the applicant to provide the right material themselves.  Worth investigating.

**Comment by Fabrizio69** [comment]
Ciao @fiorisi, can we evaluate @Lawproto 's proposal?

**Comment by pattacini** [comment]
An issue is much slimmer and serves to notify everybody that something will start soon.
To open a PR, instead, you need to do already some work.

Therefore, the ideal case is to open an issue beforehand and then do the work in a branch/fork to finally open a PR. [Issues and PR's can be linked to each other](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by fiorisi** [comment]
> Ciao @fiorisi, can we evaluate @Lawproto 's proposal?

Discussed F2F with @Lawproto.
The main issue is that the file are binary, and the reviewer would have to change the remote or clone the fork. We will commit the files and keep this issue open to align with @Elio75.

**Comment by pattacini** [comment]
>The main issue is that the files are binary,

That's true and binary files cannot be compared within the PR dashboard of course.
However, a PR still represents a moment in time when a delivery is complete, thus a resource that can be referenced and used later.

Just wanted to highlight all the pro's and cons'.

**Comment by Lawproto** [comment]
@Elio75 I backupped `ecub_004_a_004` and `ecub_004_a_005` in this repo, ergocub_sn_000 branch, and committed (see above).
They have to be mounted on the robot, waiting for your feedback.

**Comment by Elio75** [comment]
Both lower arms fitted

![image](https://user-images.githubusercontent.com/53298662/203495039-93cfe416-6e7e-410f-a915-0b6b7a0b3a2d.png)


CC @Fabrizio69 @Lawproto

**Comment by Lawproto** [comment]
@Elio75 do you think we can close this one?
