### ISSUE TITLE
ergocub_sn_000 - add a note

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/robot-snapshots#14]
**Applicant:** @salvi-mattia 

**Snapshot name:** [ergocub_sn_000](https://github.com/icub-tech-iit/robot-snapshots/tree/ergocub_sn_000)

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
In order to fit ECUB_003_P_137 in ECUB_003_P_070, ECUB_003_P_030 and ECUB_003_P_134
we removed some material from the internal surface of ECUB_003_P_137 in the physical robot.
So if we are going to mount brand new stator cases they won't fit unless we remove some material from that surface.

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
this note is added to the snapshot

**Comment by Elio75** [comment]
DONE

I put the note on [README](https://github.com/icub-tech-iit/robot-snapshots/blob/ergocub_sn_000/README.md)

CC @Fabrizio69 @salvi-mattia @fbiggi
