### ISSUE TITLE
[ergoCub_sn_000] [introducing shims for LCORE positioning - Left Hip Pitch Lower body]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#20]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *platform_sn_xxx*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
[Introduction of shims for better positioning of the LCORE board on the left hip optic disc.]

[Optional table]

| Alias / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|MYONIC_SHIM_PS_2_3-5_THK_0-1 / 13531  | 2 | Myonic Precision Shim PS 2.25 x 3.2 mm thickness 0,10 mm |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
Concrete solution to the problem

**Comment by Elio75** [comment]
Two shims were added for the positioning of the Lcore board in order to be able to read the left hip optical disc lower body.

![image](https://user-images.githubusercontent.com/53298662/215123716-2c869476-abb8-4e8c-b1cf-73e07c9f21b8.png)

Work in progress

@Fabrizio69

**Comment by Elio75** [comment]
we disassembled the left leg to check the validity of the optical disk, the latter was found to be rifled so it was not a problem with the sensor placement of the Lcore board so the shims were removed.

CC @Fabrizio69

**Comment by Fabrizio69** [comment]
@Elio75 we can close this issue
