### ISSUE TITLE
[ergoCub_SN_000] [modifying RealSense flat support and retainer]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#24]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergoCub_SN_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Redesigning the components, and adding the pivot point, I am going to re-send them to production. See [reference issue](https://github.com/icub-tech-iit/fix/issues/1326).

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| IC_014_P_151 - 15730.A1 | 1 | ergoCub head, RPLiDar support, flat cable RealSense locker |  |
| IC_014_G_197 - 16514.A2 | 1 | ergoCub head, RPLiDAR USB adapter, support |  |

## Definition of Done

- [x] Replace `IC_014_P_151 - 15730` with` IC_014_P_151 - 15730.A1`
- [x] Replace `IC_014_G_197 - 16514.A1` with `IC_014_G_197 - 16514.A2`
- [ ] update WinGST job

**Comment by Mick3Lozzo** [comment]
@Fabrizio69 the WinGST BOM and orders have to be updated, correct?

**Comment by Mick3Lozzo** [comment]
@Fabrizio69 the WinGST BOM and orders have to be updated, correct?

**Comment by Fabrizio69** [comment]
@Mick3Lozzo the WinGST BOM has to be updated. Orders are currently for CUST and SHTM parts only, so no changes are needed for the components in the [table](https://github.com/icub-tech-iit/robot-snapshots/issues/24#issue-1605207902)

**Comment by Elio75** [comment]
CAD UPDATE DONE

![image](https://user-images.githubusercontent.com/53298662/225647672-57cbdff5-3a19-4f40-95f1-ee055d30e0b8.png)

cc @Fabrizio69 @Mick3Lozzo
