### ISSUE TITLE
[ergoCub_sn_000] [Update the right and left lowerarms]

### ISSUE THREAD

**Issue by fiorisi** [icub-tech-iit/robot-snapshots#26]
**Applicant:** Luca Fiorio, @fiorisi 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
We have to modify the snapshot as per these hardware modifications:
- right lowerarm: https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/133#issuecomment-1471891835
- left lowerarm:
  - https://github.com/icub-tech-iit/proto/issues/2150#issuecomment-1478974132
  - https://github.com/icub-tech-iit/proto/issues/2150#issuecomment-1479553049

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
CAD model of the snapshot updated.

**Comment by Lawproto** [comment]
I created the expanded Ø9 bushing and normalizzata, `IC_021_P_037`.

![immagine](https://user-images.githubusercontent.com/84333301/227491630-11b1df95-72d6-4aa5-bfaa-4efb5cff8db1.png)

**Comment by Lawproto** [comment]
with the latest commit above, the snapshot is up to date.
cc @fbiggi @Fabrizio69 @fiorisi 
Closing.
