### ISSUE TITLE
[ergoCub_sn_000] [update speaker mounting]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#27]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
We have to update the speaker mounting as per https://github.com/icub-tech-iit/project-ergocub/issues/83#issuecomment-1500283417.

I have corrected the mask and increased the revision, but we have to add the washers in the snapshot, as done by @fbiggi.

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 4589 | 2 | Hexagonal nut, M3, nylon, DIN934, ISO4032, UNI5588 |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
The CAD model of the snapshot has been updated.

**Comment by Elio75** [comment]
![image](https://user-images.githubusercontent.com/53298662/234881084-87d0587a-e4a0-42e0-abd6-559da014f088.png)

@Fabrizio69
