### ISSUE TITLE
[ergocub_sn_000] Update neck group ergoCub_sn_000

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#29]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Updated neck assembly with new attachment modification between omega and planetary neck pulley.

![image](https://user-images.githubusercontent.com/53298662/232543799-8d35d831-9c74-4569-8b0d-305ad1333702.png)

Then replace in the neck assembly (Alias IC_014_G_180 cod.15716):
- RC_IIT_010_P_024 cod.2568.A1 with RC_IIT_010_P_090 cod.17192
- RC_IIT_010_P_008 / 2554.A3 with RC_IIT_010_P_091 cod.17193
- RC_IIT_010_P_069 cod.6213.A1 with RC_IIT_010_P_092 cod.17194
- S3-6--_-_I2338_B cod. 12508 2 pz
- M3X14-6LOBE-ISO14583-A2-70 cod. 16027 2 pz

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
Upgrade snapshot CAD 3D

## Info
[
Head change the OMEGA (neck diff idlepulleys main frame) fixing](https://github.com/icub-tech-iit/proto/issues/2132#issue-1608875296)

**Comment by Elio75** [comment]
Updated neck assembly IC_014_G_180 on snapshot ergocub_sn_000

![image](https://user-images.githubusercontent.com/53298662/233402939-7f0a2598-2446-4a73-ad83-c93b5e60e5af.png)

CC @Fabrizio69

**Comment by maggia80** [comment]
@Fabrizio69 @Elio75 I think we should build these parts also for ergoCub 001 and 002. Can we open a MWS commessa?

**Comment by Elio75** [comment]
@maggia80, yes , we did it for the other robots (sn), [[MMWS 2023-020 ID 8078 ]](https://github.com/icub-tech-iit/proto/issues/2153#issue-1625463130)

CC @Fabrizio69

**Comment by maggia80** [comment]
great!!!

**Comment by Fabrizio69** [comment]
Thanks @Elio75, are these parts also on the ergoCub1.1 CAD?

cc: @maggia80
