### ISSUE TITLE
[ergoCub_sn_000] [add Xsens IMU and its related support to waist]

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#31]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergoCub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
As per https://github.com/icub-tech-iit/tickets/issues/2684 , add to assembly `15789 - ECUB_003_G_020` the components indicated below ~and increase to `A1` in its revision~. These components are already mounted on the real robot and the `cad-mechanics` model is updated.

<img src="https://user-images.githubusercontent.com/15085666/233601286-51ef25d0-21a7-4d87-a3dd-a8ff4dd9f1b5.png" width="400">

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 17297 - ECUB_003_G_152 | 1 | ergoCub, waist, Xsens holder |  add component |
| 17298 -  XSENS_MTI-630-AHRS  | 1 |  Inertial sensor MTi-630-AHRS | add component | 
| 3385  -   V3-8--_-_ISO7046-1_CH | 3 | screw – M3 x 8  – UNI7688 | add component |
| 2423  -   V2-12--_-_ISO7045_CZ | 3 | screw – M2 x 12  – UNI7687 | add component |

## Definition of Done
Add `17298`, `17297` and all related screws, as indicated above.

## Commit

[added xsens_mti-630-ahrs & support](https://github.com/icub-tech-iit/robot-snapshots/commit/f44d848f84e6ea6301f9e5b1685c4b46260e368a)

**Comment by Elio75** [comment]
Xsens and its support were mounted on the assembly ECUB_003_G_020 

![image](https://user-images.githubusercontent.com/53298662/235119266-e646a32c-448a-47a7-a97e-490b0c0ba6b7.png)

@Fabrizio69 @Mick3Lozzo
