### ISSUE TITLE
[ergocub_sn_000] [CAD update neck cable]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#32]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Update Cad of the neck with Ø 0.81 uncoated steel cable AISI 304. 

Material used for the construction of the cable

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|4722  | 4 | THIMBLE FOR CABLE n0.8mm |  |
| 4482  | 1 mtr | Stainless steel microcable, cable construction 7x7mm, nom. dia 0,81mm, not coated, AISI 304 |  |
|5964  | 1 | Head Cable B - 312 mm |  | 

## Definition of Done
CAD updated and the new part normalized to Wingst

## Resume

New Neck Head Cable

| Item / IITCODE |  Description | Notes  |
|:---:|:---:|:---|
| IC_014_G_202 / 17309 |  neck cable Ø 0.81, 312 mm  |  |
|  IC_014_R_003 / 17311 | Head, neck cable |  |  

BOM 17309

## Info

[Costruzione tendini testa eCub s/n 000 prototipi Head cable "A" IIT CODE 5965MOD-Head cable "B" CODE 5964MOD](https://github.com/icub-tech-iit/proto/issues/2133#issue-1612944687)

[WAREHOUSE - Sostituzione cavo collo 4964 Ecub s/n 000](https://github.com/icub-tech-iit/tickets/issues/2756#issue-1611046132)

## Commit

[Added and replaced the new neck cable](https://github.com/icub-tech-iit/robot-snapshots/commit/8c7c061e3912813441b078f4ab06357b5a11a9d2)

[added ic_014_r_003.asm](https://github.com/icub-tech-iit/robot-snapshots/commit/7560f36f759459e6ab1e5e8743afc89fc6590fc2)

**Comment by Elio75** [comment]
The cables, cable head **A** RC_IIT_019_G_018 cod 5965 and cable head **B** RC_IIT_019_G_017 cod 5964 have been replaced with Alias cable IC_014_G_202 cod 17309 in the snapshot ergocub_SN_000

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/a0eb9209-d1f3-4ce2-8072-661acfd9d5eb)

@Fabrizio69 @GiacomoVassallo13

**Comment by Fabrizio69** [comment]
Hi @Elio75 , this tendon cod.17309 is an ASM but it's not a BOM in WinGST:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/9ab6a75a-6075-4f11-aa00-8afa22e9b270)

**Comment by Fabrizio69** [comment]
@Elio75 have you checked the BOM?

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/3de12a17-4044-400d-a453-7877ae26904c)

Do we need to buy a new custom cable (IC_014_P_203)?????

**Comment by Elio75** [comment]
The cable IC_014_G_202 cod 17309 is configured at the CAD level in the following form:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/d0f92b51-eea1-4a4a-bace-99c92267241c)

BOM 17309 at Wingst level:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/9445e16d-902a-427c-bb01-399a98028e67)


CC @Fabrizio69

**Comment by Elio75** [comment]
Ok ho risolto pare non abbia salvato il file che avevo modificato, ora è a posto 

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/d5490025-0f2f-4fd9-9ed1-6f428bc6b5f1)

CC @Fabrizio69

**Comment by Fabrizio69** [comment]
Ciao @Elio75 puoi linkare a questa issue il commit fatto... grazie
