### ISSUE TITLE
[ergoCub_SN_000] [Implementation for better cooling on the upper body]

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#34]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *ergocub_sn_000*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Implementation of three fans plus support on the robot torso in order to help with cooling and improve temperature dissipation

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| ECUB_004_P_054_SN_000 | 1 | Support fans |  |
| FAN_25X25X8 / 6784 | 3 | Fan 12VDC, screw mount, 25x25x8mm |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
CAD update design and assembly validation on ergocub_sn_000

## Info

[ergoCubSN000 – Motor temperature suspiciously high around some joints](https://github.com/robotology/icub-tech-support/issues/1528)

°° Commit

[added new fan plate design ecub_004_p_054_sn_000](https://github.com/icub-tech-iit/robot-snapshots/commit/72dca22079ddfd814beac7db23afdea3f2d83686)

[modified cover, added holes](https://github.com/icub-tech-iit/robot-snapshots/commit/60cb9894c81071d77b823cd7cfae6b5841f95cdf)

[created new alias with sn_000 suffix](https://github.com/icub-tech-iit/robot-snapshots/commit/f368bd9132884119be97ebaa7d7f925fbbc02a1d)

## Resume

Support plate fan ECUB_004_P_054_SN_000 cod. 17371

**Comment by Fabrizio69** [comment]
Ciao @Elio75, in [your table](https://github.com/icub-tech-iit/robot-snapshots/issues/34#issue-1715833790), the description for cod.6784 - FAN_25X25X8 is wrong:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/e6612ca8-ceab-48dd-9c73-ba66c887190d)

Here you can find the right description:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/67feb854-3305-49b4-b5bc-85e83e86188d)

I corrected the table

**Comment by fbiggi** [comment]
Eseguiti insieme a @maggia80 modifica sul particolare ECUB_007_P_010
N5 fori parte anteriore (vs petto) D 8mm
N2 fori D 8mm parte posteriore
N1 foro D10mm lato sx
N1 foro D10mm lato dx


![906caa43-2186-437a-a1bb-eafb7eb253c2](https://github.com/icub-tech-iit/robot-snapshots/assets/20420331/eaf66e4d-396d-499c-af79-820580597413)

@Fabrizio69 @pattacini

**Comment by Elio75** [comment]
Ho canbiato la descrizione sia sullo snapshot che su CAD libraries

**Comment by Elio75** [comment]
Abbiamo piazzato 3 ventole tra il busto (parte bassa) e il giunto Pitch del torso robot. La zona scelta si presentava meno critica rispetto ad altre come tipologia di lavoro e criticità.
Lo spazio all'interno molto fitto tra la cover i cavi e la rotazione del giunto YAW del torso. Per questo motivo bisognava configurare la posizione delle ventole e il disegno della piastra in modo tale da non avere compenetrazioni sia con le cover sia con la meccanica del giunto PITCH durante la rotazione dello YAW.

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/f814a6ed-9bdc-4546-a0f1-ed86e65cc21f)

**Comment by Fabrizio69** [comment]
Ciao @Elio75, riporterei sullo snapshot anche la modifica fatta da Filippo sulla cover in silicone (vedi [commento](https://github.com/icub-tech-iit/robot-snapshots/issues/34#issuecomment-1554486424))

**Comment by Elio75** [comment]
> riporterei sullo snapshot anche la modifica fatta da Filippo sulla cover in silicone

Fatto

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/7a066b63-5b6a-4f83-aba6-dad9f1042c6d)

**Comment by Fabrizio69** [comment]
Ciao @Elio75 , sarebbe utile riportare il riferimento del commit, il codice e l'alias generato. Questo farebbe capire subito cosa è stato fatto.

In questo caso specifico, ho scaricato lo snapshot del robot, sono andato a cercare il particolare e vedo che:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/7c8aebcb-9991-4420-a425-48ad85134847)

Hai creato una nuova revisione del codice ECUB_007_P_010 (rev.A1) contrariamente a quanto previsto dalla [snaphot procedure](https://github.com/icub-tech-iit/procedures/wiki/Robot-Snapshot#to-avoid-in-snapshot-repository).

Per scrupolo poi ho scaricato la repository del CAD e vedo che in realtà non hai cambiato la revisione.
Pensavo questa cosa perchè a WinGST esiste solo questo:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/0f47b8c5-b3e4-4b61-89b6-287d7bf9e603)

Riporto qui il CAD di ergoCub1.1:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/78fccb40-efd4-44c9-ada7-7e68b17b6aa7)

Quindi questa cosa per favore va sistemata.

Altra cosa che noto che non va bene è che questo componente è un PLAS, ma questo vedo di segnalarlo a chi sta gestendo le cover. Grazie mille

**Comment by Elio75** [comment]
Creato nuovo alias [ECUB_007_P_010_SN_000](https://github.com/icub-tech-iit/robot-snapshots/issues/34#issuecomment-1557106627) al capuccio in gomma del collo. La parte è stata modificata solo sullo snapshot di ergocub_sn_000 e di conseguenza il suo alias come indica la procedura.

CC @Fabrizio69

**Comment by Fabrizio69** [comment]
Ciao @Elio75 direi che a questo punto si possa chiudere questa issue... grazie mille
