### ISSUE TITLE
ergoCub1.1_sn_002 Snapshot creation

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/robot-snapshots#37]
**Applicant:** *Fabrizio Larosa*, @Fabrizio69 

**Snapshot name:** *ergocub1.1_sn_002*

**Field of application:**
- [X] Mechanics
- [x] Electronics
- [x] Wiring

## Request Update Description
Create the snapshot for eCub1.1 S/N:002 platform

| IITCODE/ALIAS | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 16864.A1/ECUB | 1 | ergoCub1.1 assembly |  |

## Definition of Done
The mech. CAD snapshot is created (new branch in the snapshot repo) and the BOM is imported in WinGST:
Cod. 16864.A1 - ECUB rev.A1 - ergoCub 1.1 , assembly | ASM

The electronic parts (logic schematics): [ergoCub1.1_Logic_17256_1.1.0.pdf](https://github.com/icub-tech-iit/electronics-wiring/blob/master/ergocub1/ergocub1.1/pdf/ergoCub1.1_Logic_17256_1.1.0.pdf)

The wiring parts (harness schematics): [ergoCub1.1_Harness_17257_1.1.0.pdf](https://github.com/icub-tech-iit/electronics-wiring/blob/master/ergocub1/ergocub1.1/pdf/ergoCub1.1_Harness_17257_1.1.0.pdf) (see [issue](https://github.com/icub-tech-iit/robot-snapshots/issues/36#issuecomment-1660487295))

**Comment by Elio75** [comment]
@Fabrizio69 BOM creata di ecub1.1 cod. 16864.A1

**Comment by Elio75** [comment]
Creato snapshot ergocub1.1_SN_002
Commit linkato al commento come si può vedere sotto ↓

**Comment by Elio75** [comment]
## Last reference commit

- CAD-mechanics
  &#x21B3; [Fix typo in revision (from A1 to A2).](https://github.com/icub-tech-iit/cad-mechanics/commit/0913f5666d8d972a9e1107650639f4d6da9198b3)

- CAD-libraries
  &#x21B3; [updated wrong weight](https://github.com/icub-tech-iit/cad-libraries/commit/be5d51953086f5d8076a4125d5d8eab4949a5a34)

CC @fiorisi

**Comment by Fabrizio69** [comment]
I reopen this issue for the electronic and wiring snapshots. I add also all reference info in the OP...

**Comment by Fabrizio69** [comment]
Ciao @maggia80 , in the electronics BOM (logic schematics) there is AMO1 rev.A (cod.6778.A), but this board now is not available (AMO1 is on the eCub1.1 S/N:001 platform). We have AMO1 rev.B:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/d6ca1378-8d27-4ce2-9e59-68ebd1ab6c98)
 
Does this board replacement my affect firmware/software or something else?

cc: @Nicogene @pattacini

**Comment by pattacini** [comment]
>Does this board replacement my affect firmware/software or something else?

Probably not, but worth checking.
Maybe @davidetome knows it.

**Comment by davidetome** [comment]
> Probably not, but worth checking.
Maybe @davidetome knows it.

I think so but @maggia80 can surely confirm,

cc @Fabrizio69

**Comment by maggia80** [comment]
AMO1 rev.B is fine as well. The EEPROM is used by the iC-MU sensor for storing data about the calibration and some other options. It does not affect the communication between the AMO1 and the EMS4, so there isn't any firmware/software change needed.

**Comment by Fabrizio69** [comment]
Thanks @maggia80! If there isn't any firmware/software change needed , we can mix on this robot cod.6778 rev.A (latest available and already withdrawn automatically, from the warehouse) with cod.6778 rev.B . OK we'll proceed in this way. Thanks

**Comment by Fabrizio69** [comment]
According to [this comment](https://github.com/icub-tech-iit/purchases/issues/2376#issuecomment-1699438503): the MMA boards (cod.16872.A) are replaced by cod.16872.B.

**Comment by Elio75** [comment]
readme electronic ergocub_sn_002 (MMA / AMO1) updated 

cc @Fabrizio69
