### ISSUE TITLE
ergoCub_sn_001/002 - waist front and back covers and supports

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#40]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergoCub_sn_001*, *ergoCub_sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
As per [this comment](https://github.com/icub-tech-iit/project-ergocub/issues/121#issuecomment-1664020830) at last we decided to:

- Modify the front waist and IMU cover.
- Modify the IMU support.
- Remove from the CAD the back waist cover (that has never been sent to production, though). 

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/15085666/4bd8d7d9-bdfd-4e54-b57c-75a6fbc73caa)

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/15085666/e3a64faf-f047-4115-aa96-a0e6b80c3b79)

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| ECUB_007_P_154 / 17564 | 1 | waist and Xsense cover |  |
| ECUB_003_G_155 / 17620 | 1 | ergoCub, waist, Xsens holder |  |
|  |  |  |  | 

## Definition of Done
 - Replace `17297 - ECUB_003_G_152` with `17620 - ECUB_003_G_155` in `15789.A2 - ECUB_003_G_020`.
 
- [x] sn_001
- [x] sn_002

 - Remove `16896 - ECUB_007_P_004` from `16928.A1- ECUB_007_A_001` and its related n° 4 screws `16022 - M3X06-6LOBE-ISO14583-A2-70` [^1].

- [x] sn_001
- [x] sn_002

 - Add to `16928.A1- ECUB_007_A_001` the front cover `17564 - ECUB_007_P_154` and  n° 2 screws `15833 - M3X10-6LOBE-ISO14581-A2`.
 
- [x] sn_001
- [x] sn_002
 

 - Update production BOMs and orders @Fabrizio69.

[^1]: These components have **never** been sent to production.

**Comment by Mick3Lozzo** [comment]
@Fabrizio69 before working on this issue we should send the components to production. 
I have already sent them to production n° 3 `17620 - ECUB_003_G_155`, and I will put them in the warehouse when they are available.

**Comment by Elio75** [comment]
@Mick3Lozzo sui sn_001 / sn_002: 

-  >Sostituisci 17297 - ECUB_003_G_152con 17620 - ECUB_003_G_155in 15789.A2 - ECUB_003_G_020.
   - Vorresti dire sostituisci ECUB_003_G_153 con ECUB_003_G_155 ? vero?

@pattacini @Fabrizio69

**Comment by pattacini** [comment]
/remind September 11 @Mick3Lozzo please address @Elio75 [request](https://github.com/icub-tech-iit/robot-snapshots/issues/40#issuecomment-1697340962).

**Comment by Elio75** [comment]
Modifiche CAD sn_002 &#x2192; **FATTO**

@Mick3Lozzo @Fabrizio69

**Comment by Elio75** [comment]
Modifiche CAD sn_001 → FATTO

@Mick3Lozzo @Fabrizio69

**Comment by Elio75** [comment]
@Mick3Lozzo 

 >Update production BOMs and orders

see [comment](https://github.com/icub-tech-iit/robot-snapshots/issues/40#issuecomment-1693052770)

**Comment by Elio75** [comment]
Chiudo
