### ISSUE TITLE
ergoCub_sn_002 - AEA3 support and neck pitch hard stop

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#41]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergoCub_sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
As per [this issue](https://github.com/icub-tech-iit/proto/issues/2515) to the neck AEA3 group, the same modification has to be applied on the ergoCub snapshots too.

<img src="https://github.com/icub-tech-iit/fix/assets/15085666/b83901b8-f50f-4fb5-87d7-eb8f7714f7e2" width="300">

 > **NOTE**:
 > This modification is still a work in progress, has to be tested and eventually sent to production.

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  IC_014_P_205 / 17636 | 1 |  AEA3 holder and neck pitch hard stop |  |
| IC_014_G_182 - 15718.A3 /  |  1 | neck tilt AA encoder PCB support |  |

## Definition of Done

CAD update of the neck with new AEA support

**Comment by Mick3Lozzo** [comment]
@Elio75 @Fabrizio69 this solution still has to be tested and the components have not ever been sent to production.

**Comment by Nicogene** [comment]
Putting on hold until @Mick3Lozzo returns

/remind 11 september

**Comment by Elio75** [comment]
Comunque prima di modificare / unificare dei pezzi in modo da semplificare il sistema , io proverei a migliorare solo il supporto

**Comment by Elio75** [comment]
## CAD update of the neck ergocub_sn_002
