### ISSUE TITLE
ergoCub_sn_001/002 - neck roll motor holder

### ISSUE THREAD

**Issue by Mick3Lozzo** [icub-tech-iit/robot-snapshots#42]
**Applicant:** *Michele Gesino*, @Mick3Lozzo 

**Snapshot name:** *ergoCub_sn_001*, *ergoCub_sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/15085666/0a1d45c6-c9e5-4937-82e4-9e30369a1a2e)

~Modify 2607.A1 - RC_IIT_010_P_023 as per [this comment](https://github.com/icub-tech-iit/proto/issues/2456#issuecomment-1690123817) and [this other comment](https://github.com/icub-tech-iit/proto/issues/2456#issuecomment-1690087852).~

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| RC_IIT_010_P_023 / 2607.A1 | V2 neck pan motor holder |  |  |
|  |  |  |  |

## Definition of Done

~- [x] Define with @GiacomoVassallo13 the modifications to `2607.A1`.~
~- [x] Update official CAD, increase `2607` revision to `A2`.~

- [x] Turn the neck support with the motor cable at the front Alias RC_IIT_010_G_011
- [x] Update snapshots `001` and `002` @Elio75 

~- [ ] Send components to production.~
~- [ ] Update BOMs and orders @Fabrizio69.~

**Comment by Mick3Lozzo** [comment]
On hold, modifications still to be defined, see [this comment](https://github.com/icub-tech-iit/proto/issues/2456#issuecomment-1693193110).

**Comment by Elio75** [comment]
Scusate ma forse bastava girare il pezzo di 180° per far passare il flat sul davanti senza dover fare nessuna modifica.

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/663b780a-88ff-4b24-8258-a303dd8e9a01)

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/5101a60b-d6ea-4298-9e93-f4ba3d87b2ce)

@Mick3Lozzo

**Comment by Elio75** [comment]
Ho riportato la modifica su ergocub_sn_001

**Comment by Elio75** [comment]
[](url)

**Comment by Elio75** [comment]
Insieme a @fiorisi abbiamo deciso di: 

- fare una prova a CAD girando il pezzo RC_IIT_010_P_023  insieme al motore di 180° in modo da verificare che no ci siano problemi di compenetrazione o di montaggio degli altri gruppi permettendo ai cavi di uscire sul davanti. Questo potrebbe risolvere il problema visto che il pezzo si presenta simetrico in quasi la sua totaslità e cosi evitare altre modifiche su questo ultimo.

CC @Fabrizio69 @GiacomoVassallo13 @Nicogene @Gandoo

**Comment by Elio75** [comment]
## Prova CAD

- Ho sovraposto l'assieme IC_014_G_181 uno a 0° e l'atro a 180°, come si può vedere dalla immagiene i fori di fissaggio e fori spinati combaciano entrambi lati.

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/91a868ca-3836-41a7-863c-676fa59d0642)

- La parte inferiore del collo rispetto a quella superiore viene montata mediante due spine controposte e il anello clamp che li tiene insieme, perciò la parte inferiore può essere girata senza problemi visto che l'accopiamento viene fatto tra la wave generator e la flexpline del HD e le due superficie di contatto di entrambi gruppi.

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/d692c4a8-7445-4da3-aa1e-dd93ed29fb65)

**Comment by Mick3Lozzo** [comment]
> ## Prova CAD
> * Ho sovraposto l'assieme IC_014_G_181 uno a 0° e l'atro a 180°, come si può vedere dalla immagiene i fori di fissaggio e fori spinati combaciano entrambi lati.
> 

@Elio75 ripristino la versione precedente di `RC_IIT_010_P_023` incluso il disegno, e monto ribaltato di 180° `RC_IIT_010_G_011` dentro l'assieme `IC_014_G_181`.

**Comment by Mick3Lozzo** [comment]
@Elio75 fatto, dovrebbe essere tutto a posto.

**Comment by Elio75** [comment]
CAD a posto collo girato... ora farò lo stesso sugli snapshot

**Comment by Fabrizio69** [comment]
Ciao @Elio75, ma sullo snapshot di eCub1.1 S/N:001 questa modifica deve essere riportata?
Il collo dell'iCub1.1 S/N:002 deve ancora essere assemblato, ma quello del S/N:001 è già costruito...

**Comment by Elio75** [comment]
Si bisognerà farlo sul sn_001 / 002

**Comment by Elio75** [comment]
Il supporto motore del collo IC_014_G_181 è stato girato con il cavo uscente sul davanti

**Comment by Elio75** [comment]
## Snapshot ergocub_sn_001

Ho ripristinato a CAD il collo del sn_001 rispetto quello fisico già montato e colaudato. Il pezzo RC_IIT_010_P_023 cod2607.A1 non è stato girato rispetto al suo omologo sn_002 ma il motore (YAW) si portando sul davanti l'uscita dei cavi.

**Comment by Elio75** [comment]
Il supporto motore neck roll girato di 180° è stato montato da @GiacomoVassallo13 sull'assieme testa ergocub_sn_002. Il montaggio è avvenuto con successo, non sono state  risscontrate anomalie.


https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/e438a784-e7e7-4221-be6c-73d3aaf8f46f

**Comment by Elio75** [comment]
Direi che la modifica di montaggio va bene, la issue si può chiudere
