### ISSUE TITLE
[ergocub_sn_000] Calf support , replace screw fixing with  high-strength screws 10.9 / 12.9

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#45]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *ergocub_sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Replace the A2 screws fixing the calf support to the Harmonic driver with high-strength screws 12.9

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/0c9fa38f-7da0-4f6a-b29c-01ed96a38a62)

## Screws to be replaced class A2

- V8-20--_-_U5933_C cod.10542
- V3-40--_-_U5931_GP cod.10235

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| Alias M3X40-P-ISO4762-12_9-BLACK / cod17189 | 24 | Hexagon socket head screw ISO4762 - M3x40 - partially threaded - 12.9 black |  |
|Alias M8X20-ISO10642-10_9-BLACK / 17246  | 16 | Hex socket flat countersunk head screw ISO10642 - M8x20 - 10.9 black |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
Update CAD ergocub_sn_000
- Upgrade the following assemblies with high-strength screws
  - [x] ECUB_003_G_030
  - [x] ECUB_003_G_050
  - [x] ECUB_003_G_060
  - [x] ECUB_003_G_070

**Comment by Elio75** [comment]
Ho aggiornato il CAD con delle viti ad alta resistenza 10.9 / 12.9

CC @Fabrizio69 @fbiggi

**Comment by Elio75** [comment]
Chiudo

**Comment by Fabrizio69** [comment]
Ciao @Elio75 avrei indicato anche il codice (oppure i codici) delle viti che hai sostituito

**Comment by Elio75** [comment]
[Fatto](https://github.com/icub-tech-iit/robot-snapshots/issues/45#issue-1910914665)

**Comment by Fabrizio69** [comment]
Grazie @Elio75 a questo punto direi si possa chiudere questa issue.
