### ISSUE TITLE
ergoCub1.1_sn_001 Added CAN_TERM boards (cod.17662.A)

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/robot-snapshots#48]
**Applicant:** *Fabrizio Larosa*, @Fabrizio69 

**Snapshot name:** *ergoCub1.1_sn_001*

**Field of application:**
- [ ] Mechanics
- [X] Electronics
- [X] Wiring

## Request Update Description
According to [these changes](https://github.com/icub-tech-iit/proto/issues/2542) for eCub1.1 S/N:001 the harness and the logic diagrams have to change

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done
The snapshot is updated (New harness and new Logic diagrams)

**Comment by AntonioAzocar** [comment]
Added the Can_term board (cod. 17622.A) between EB21 and RFE (**HEAD**)

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/130973726/e96b1c5e-ca52-4e47-a39a-5af90e8eec3a)


cc @Fabrizio69 @maggia80

**Comment by AntonioAzocar** [comment]
Check here for the updated logic & harness diagrams:

- https://github.com/icub-tech-iit/electronics-wiring/commit/e87cc780e63e43fef0e5846e34aa3593712a770c

**Comment by AntonioAzocar** [comment]
So, now I think we can close this issue @Fabrizio69

**Comment by Fabrizio69** [comment]
Hi @AntonioAzocar, this issue is for eCub1.1 S/N:001 changes and I don't see changes in the snapshot for this robot... 

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/02a4725e-2b7d-4bd2-ad62-f24a3f948e16)

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/12031391/d83dfc64-3a0d-41d4-9875-8a121cbb3271)

**Comment by AntonioAzocar** [comment]
Done!
Now you can see the logic & harness diagrams updated

- https://github.com/icub-tech-iit/robot-snapshots/commit/cf686108cff6f091a72b25e35621b9ba00eee82d
