### ISSUE TITLE
[ergocub_sn_002] New support AEA -Fore arm - Alias IC_021_G_186 cod. 17682

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#56]
**Applicant:** *Elio Massa*, @Elio75 

**Snapshot name:** *ergocub_sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Replace AEA holder aka IC_021_G_049 cod.16366 with aka IC_021_G_186 cod. 17682 on left and right forearm.

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/cd84aec3-8a14-4128-9d9f-7b3b621265e4)

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
| 17682 /IC_021_G_186 | 2 | lower arm, frame cover support with inserts |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done

- [x] snapshots CAD update  ergocub_sn_002

**Comment by Elio75** [comment]
Update CAD snapshot ergocub_sn_002

**Comment by Fabrizio69** [comment]
See the [changes on the robot](https://github.com/icub-tech-iit/proto/issues/2589#issuecomment-1824500433)
