### ISSUE TITLE
[ergocub_sn_000  -  ergocub_sn_001  -  ergocub_sn_002] [Update feet soles]

### ISSUE THREAD

**Issue by fiorisi** [icub-tech-iit/robot-snapshots#57]
**Applicant:** *Masa Salvi*, @salvi-mattia 

**Snapshot name:** 
- *ergocub_sn_000*
- *ergocub_sn_001* -> `Note`: assemble also on the real robot
- *ergocub_sn_002* -> `Note`: assemble also on the real robot

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Replace the feet soles as described in https://github.com/icub-tech-iit/project-ergocub/issues/132#issuecomment-1829875090. 

[Optional table]

| Alias | Quantity for one robot |  Description | Rev |
|:---:|:---:|:---|:---|
| ECUB_003_P_047 | 4 |  | A1 |
| ECUB_003_P_050 | 4 |  | A1 |
|  |  |  |  | 
|  |  |  |  |

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/8970230/c44bd647-5f51-4f75-b842-5f83246acfb3)

## Definition of Done
- [x] snapshots SN000, SN001 and SN002 updated
- [ ] [Real robot SN001 and SN002 updated](https://github.com/icub-tech-iit/proto/issues/2652#issue-2026105019) replaced by this [issue](https://github.com/icub-tech-iit/proto/issues/2650)

**Comment by Elio75** [comment]
**Update CAD snapshot ergocub_sn_001**

**Comment by Elio75** [comment]
**Update CAD snapshot ergocub_sn_002**

**Comment by fiorisi** [comment]
>  Real robot SN001 and SN002 updated

@Elio75 concerning this point did you open a dedicated issue?

**Comment by Elio75** [comment]
Scusa l'ho chiusa per sbaglio

**Comment by Fabrizio69** [comment]
Gli snapshot sono stati aggiornati, procediamo con la chiusura di questa issue rimandando a [ergoCub1.1 S/N:001 - Install the new soles (cod.16018.A1, cod.16587.A1)](https://github.com/icub-tech-iit/proto/issues/2650) per l'installazione sul robot

**Comment by Elio75** [comment]
Ho aggiunto una NOTA (TOOL) sul albero modello per l'uso del tool IT_004_G_001 durante il montaggio delle suole dei piedi. Questo sui robot ergocub_sn_001 / ergocub_sn_002

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/6423d2ea-e500-4074-ac2f-918aa355968f)

**Comment by fiorisi** [comment]
> Ho aggiunto una NOTA (TOOL) sul albero modello per l'uso del tool IT_004_G_001 durante il montaggio delle suole dei piedi. Questo sui robot ergocub_sn_001 / ergocub_sn_002

Ottimo @Elio75. Per favore indica in modo esplicito l'alias del tool che deve essere usato. 
See the dedicated note in the [Annotation Features](https://github.com/icub-tech-iit/cad-libraries/wiki/Mechanical-design-guidelines#annotation-feature-creation-procedure) section:

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/8970230/2d748a48-f823-4acf-b358-0931fe2be18f)

**Comment by Elio75** [comment]
ergoCub_sn_001 commit
- [modified NOTE](https://github.com/icub-tech-iit/robot-snapshots/commit/b7cb17f25cf8981b4522ef3a179a794a6d3b1de9)
- [added note for Tool](https://github.com/icub-tech-iit/robot-snapshots/commit/dd3c063de8f6d5154d08770a43f3314b40b0b97e)
