### ISSUE TITLE
[ergocub_sn_001 / sn_002] replace washer code 17576- alias R2-2--_-_U6592 with code 1876 - alias R2-5--_-_U6592

### ISSUE THREAD

**Issue by Elio75** [icub-tech-iit/robot-snapshots#60]
**Applicant:** *Name Surname*, @username

**Snapshot name:** *ergocub_sn_001 / sn_002*

**Field of application:**
- [x] Mechanics
- [ ] Electronics
- [ ] Wiring

## Request Update Description
Replace the 4 washers item no.17576- alias R2-2--_-_U6592 with item no.1876- alias R2-5--_-_U6592 that crush the ring on the bearing to prevent backlash

![image](https://github.com/icub-tech-iit/robot-snapshots/assets/53298662/3d5ed416-42d1-414d-901c-fd3bb9b69603)

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done

- [x] update CAD snapshot ergocub_sn_001
- [x] update CAD snapshot ergocub_sn_002

**Comment by Fabrizio69** [comment]
Hi @Elio75 ,
Now, the snapshots for eCub1.1 S/N:001 and eCub1.1 S/N:002 are updated, so we can close this issue
