### ISSUE TITLE
eCub_sn_002 - Add NVIDIA Orin and ferrites to TDB cables

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/robot-snapshots#68]
**Applicant:** *Fabrizio Larosa*, @Fabrizio69 

**Snapshot name:** *eCub_sn_002*

**Field of application:**
- [ ] Mechanics
- [X] Electronics
- [X] Wiring

## Request Update Description

Change the diagrams for `eCub1.1 S/N:002`, with the replacement of the Xavier board (code **14615**)  with the Orin board (code **17678**) on the head.
Also, as accorded in [this issue](https://github.com/icub-tech-iit/proto/issues/2738#issue-2125289177), add ferrites (code **17820**) to the cables of the TDBs.

[Optional table]

| Item / IITCODE | Quantity |  Description | Notes  |
|:---:|:---:|:---|:---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  | 
|  |  |  |  |

## Definition of Done

- [x] New diagrams are in the snapshot repository: [add here the link]

**Comment by AntonioAzocar** [comment]
Hi! I updated the schematics of `ergoCub1.1 S/N:002` with the addition of ferrites (code **17820**) to the **TDB** cables, the replacement of the **Xavier** board with the **Orin** board and also fixed other minor things (heat shrink, cable lengths...)

Here, the commit with the updated schematics:

- https://github.com/icub-tech-iit/robot-snapshots/commit/636d7b6898fa8bd60be1b69e7e6f7f8c1e91ef46

cc @Fabrizio69

**Comment by Fabrizio69** [comment]
We can close thi issue. Thank you @AntonioAzocar
